server:
  port: 8006
spring:
  application:
    name: cloud-provider-consul-payment
#consul注册中心地址
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}