server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.96.165.167:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 277708272
    druid:
      test-while-idle: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zh.entities

eureka:
  client:
    #表示将自己注册进eureka server
    register-with-eureka: true
    #表示是否从eureka server抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka