server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment

#设置feign客户端超时时间（feign默认支持ribbon）
#ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ReadTimeout: 3000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ConnectTimeout: 3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
